### ISSUE TITLE
Определить вид первого прототипа

### ISSUE THREAD

**Issue by OnsGood** [OnsGood/playful-penguins#1]
Итак, тут заготовка проекта, как освоишься в гите бери эту задачу.
Список того, что надо сделать:
1. Описать что программа принимает на вход
1.2. Описать, что идет на выход.
2. Наличие графического интерфейса, нарисовать прототип если он будет.
3. Попытаться максимально подробно описать алгоритм гадания, если его нет, то придумать и описать.
4. Перед тем как придумывать алгоритм гадания, надо уже знать алгоритм распознавания линий на руке)

**Comment by urrival** [comment]
1. На вход подается изображение руки, заранее существующее на компьютере 
На выходе у нас будет изображение с контуром ладони и тремя основными линиями на этом контуре
2. В двух словах: благодаря Windows Form создается окошочеко. В этом окошечке есть уже обработанное изображение - контур руки, результат выхода. Справа от контура будет краткая информация - результат гадания.
3. Алгоритм гадания описан [на сайте](https://ru.wikihow.com/%D0%B3%D0%B0%D0%B4%D0%B0%D1%82%D1%8C-%D0%BF%D0%BE-%D1%80%D1%83%D0%BA%D0%B5). 4 линию брать не будем, так как она есть не у всех, а если и есть, то еле видна
